name: Bun Tests
run-name: Run Tests by @${{ github.actor }}
on:
    pull_request:
        branches:
        - dev/**
        - feature/**
        - hotfix/**
        - main
jobs:
    test:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: "canary"
            - name: Install Dependencies
              run: bun i
            - name: Run Tests
              run: bun run test