name: Test With Bun

on:
  push:
    branches:
      - main

jobs:
  run_bun:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install Bun
      run: cd src && bun install

    - name: Run Bun on app.ts
      run: bun run src/app.ts
