name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: "canary"

      - name: Install Dependencies
        run: bun i

      - name: Build
        run: bun run pack

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 4604 -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts || true

      - name: Rsync Deploy
        run: |
          rsync -az --delete \
            -e "ssh -p 4604" \
            --rsync-path="sudo rsync" \
            ./app.js \
            github@${{ secrets.SERVER_HOST }}:/srv/rxtrn

      - name: Fix Ownership
        run: |
          ssh -i ~/.ssh/id_ed25519 github@${{ secrets.SERVER_HOST }} \
            "sudo chown -R rxt:rxt /srv/rxtrn && sudo chmod -R 755 /srv/rxtrn"

      - name: Restart Service
        run: |
          ssh -i ~/.ssh/id_ed25519 github@${{ secrets.SERVER_HOST }} \
            "sudo systemctl restart rextongaming.service"
